.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH glfxc 1 "DEC 2011" Linux "User Manuals"
.SH NAME
glfxc \- A GLFX effect compiler
.SH SYNOPSIS
.B glfxc 
.I file
.I program
.SH DESCRIPTION
.B glfxc
Parses a GLFX effect file and compiles specified program
using the GLSL compiler of the local OpenGL installation.
.SH OPTIONS
NONE
.SH AUTHOR
Etay Meiri <etay.meiri@gmail.com>
