#line 2 "glfxScanner.cpp"

#line 4 "glfxScanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer glfx_create_buffer
#define yy_delete_buffer glfx_delete_buffer
#define yy_flex_debug glfx_flex_debug
#define yy_init_buffer glfx_init_buffer
#define yy_flush_buffer glfx_flush_buffer
#define yy_load_buffer_state glfx_load_buffer_state
#define yy_switch_to_buffer glfx_switch_to_buffer
#define yyin glfxin
#define yyleng glfxleng
#define yylex glfxlex
#define yylineno glfxlineno
#define yyout glfxout
#define yyrestart glfxrestart
#define yytext glfxtext
#define yywrap glfxwrap
#define yyalloc glfxalloc
#define yyrealloc glfxrealloc
#define yyfree glfxfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE glfxrestart(glfxin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int glfxleng;

extern FILE *glfxin, *glfxout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE glfxlex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-glfxlineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < glfxleng; ++yyl )\
                    if ( glfxtext[yyl] == '\n' )\
                        --glfxlineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up glfxtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up glfxtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via glfxrestart()), so that the user can continue scanning by
	 * just pointing glfxin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when glfxtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int glfxleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow glfxwrap()'s to do buffer switches
 * instead of setting up a fresh glfxin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void glfxrestart (FILE *input_file  );
void glfx_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE glfx_create_buffer (FILE *file,int size  );
void glfx_delete_buffer (YY_BUFFER_STATE b  );
void glfx_flush_buffer (YY_BUFFER_STATE b  );
void glfxpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void glfxpop_buffer_state (void );

static void glfxensure_buffer_stack (void );
static void glfx_load_buffer_state (void );
static void glfx_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER glfx_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE glfx_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE glfx_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE glfx_scan_bytes (yyconst char *bytes,int len  );

void *glfxalloc (yy_size_t  );
void *glfxrealloc (void *,yy_size_t  );
void glfxfree (void *  );

#define yy_new_buffer glfx_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        glfxensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            glfx_create_buffer(glfxin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        glfxensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            glfx_create_buffer(glfxin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define glfxwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *glfxin = (FILE *) 0, *glfxout = (FILE *) 0;

typedef yyconst struct yy_trans_info *yy_state_type;

extern int glfxlineno;

int glfxlineno = 1;

extern char *glfxtext;
#define yytext_ptr glfxtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up glfxtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	glfxleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
struct yy_trans_info
	{
	flex_int16_t yy_verify;
	flex_int16_t yy_nxt;
	};
static yyconst struct yy_trans_info yy_transition[3088] =
    {
 {   0,   0 }, {   0,3049 }, {   0,   0 }, {   0,3047 }, {   1,  82 },
 {   2,  84 }, {   3,  86 }, {   4,  82 }, {   5,  88 }, {   6,  90 },
 {   7,  92 }, {   8,  82 }, {   9,  94 }, {  10,  96 }, {  11,  99 },
 {  12, 101 }, {  13, 106 }, {  14, 121 }, {  15, 123 }, {  16, 125 },
 {  17, 127 }, {  18, 166 }, {  19,  82 }, {  20, 127 }, {  21, 170 },
 {  22, 127 }, {  23, 127 }, {  24, 209 }, {  25, 248 }, {  26, 127 },
 {  27, 287 }, {  28, 127 }, {  29, 127 }, {  30, 127 }, {  31, 326 },
 {  32, 365 }, {  33, 127 }, {  34, 404 }, {  35, 443 }, {  36, 127 },
 {  37, 482 }, {  38, 172 }, {  39, 174 }, {   0,   0 }, {   0,3006 },
 {   1,  41 }, {   2,  43 }, {   3,  45 }, {   4,  41 }, {   5,  47 },

 {   6,  49 }, {   7,  51 }, {   8,  41 }, {   9,  53 }, {  10,  55 },
 {  11,  58 }, {  12,  60 }, {  13,  65 }, {  14,  80 }, {  15,  82 },
 {  16,  84 }, {  17,  86 }, {  18, 125 }, {  19,  41 }, {  20,  86 },
 {  21, 129 }, {  22,  86 }, {  23,  86 }, {  24, 168 }, {  25, 207 },
 {  26,  86 }, {  27, 246 }, {  28,  86 }, {  29,  86 }, {  30,  86 },
 {  31, 285 }, {  32, 324 }, {  33,  86 }, {  34, 363 }, {  35, 402 },
 {  36,  86 }, {  37, 441 }, {  38, 131 }, {  39, 133 }, {   0,  30 },
 {   0,2965 }, {   0,  29 }, {   0,2963 }, {   0,  29 }, {   0,2961 },
 {   0,  30 }, {   0,2959 }, {   0,  18 }, {   0,2957 }, {   0,  19 },
 {   0,2955 }, {   0,  23 }, {   0,2953 }, {   0,  30 }, {   0,2951 },

 {   0,   0 }, {   0,  30 }, {   0,2948 }, {   0,  12 }, {   0,2946 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,  12 }, {   0,2941 },
 {   8, 422 }, {  12, 116 }, {  13, 116 }, {  11, 463 }, {  10, 114 },
 {   0,   0 }, {  12, 153 }, {  13, 153 }, {  27,  92 }, {  10, 109 },
 {   0,   0 }, {  12, 187 }, {  13, 187 }, {   0,  26 }, {   0,2926 },
 {   0,  25 }, {   0,2924 }, {   0,  24 }, {   0,2922 }, {   0,  17 },
 {   0,2920 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12, 476 }, {  13, 476 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17, 476 }, {   0,   0 }, {   0,   0 },

 {  20, 476 }, {  21, 476 }, {  22, 476 }, {  23, 476 }, {  24, 476 },
 {  25, 476 }, {  26, 476 }, {  27, 476 }, {  28, 476 }, {  29, 476 },
 {  30, 476 }, {  31, 476 }, {  32, 476 }, {  33, 476 }, {  34, 476 },
 {  35, 476 }, {  36, 476 }, {  37, 476 }, {   0,  30 }, {   0,2881 },
 {   0,   0 }, {   2, 476 }, {   0,  17 }, {   0,2877 }, {   0,  20 },
 {   0,2875 }, {   0,  21 }, {   0,2873 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,2867 }, {   0,   0 },
 {  12, 433 }, {  13, 433 }, {   0,   0 }, {  19, 480 }, {   0,   0 },
 {  17, 433 }, {   0,   0 }, {   0,   0 }, {  20, 433 }, {  21, 433 },
 {  22, 433 }, {  23, 480 }, {  24, 433 }, {  25, 433 }, {  26, 433 },

 {  27, 433 }, {  28, 433 }, {  29, 433 }, {  30, 433 }, {  31, 433 },
 {  32, 433 }, {  33, 433 }, {  34, 433 }, {  35, 433 }, {  36, 433 },
 {  37, 433 }, {   0,  17 }, {   0,2838 }, {  30, 468 }, {   0,  13 },
 {   0,2835 }, {   0,   0 }, {   0,  13 }, {   0,2832 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12, 394 },
 {  13, 394 }, {   0,   0 }, {  12, 440 }, {  13, 440 }, {  17, 394 },
 {  12, 476 }, {  13, 476 }, {  20, 480 }, {  21, 394 }, {  22, 394 },
 {  23, 394 }, {  24, 394 }, {  25, 394 }, {  26, 394 }, {  27, 394 },
 {  28, 394 }, {  29, 394 }, {  30, 394 }, {  31, 394 }, {  32, 394 },
 {  33, 394 }, {  34, 519 }, {  35, 394 }, {  36, 394 }, {  37, 394 },

 {   0,  17 }, {   0,2799 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,2793 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12, 355 }, {  13, 355 },
 {   0,   0 }, {   0,   0 }, {  10, -39 }, {  17, 355 }, {  12,   0 },
 {  13,   0 }, {  20, 355 }, {  21, 355 }, {  22, 355 }, {  23, 355 },
 {  24, 355 }, {  25, 355 }, {  26, 355 }, {  27, 355 }, {  28, 355 },
 {  29, 355 }, {  30, 355 }, {  31, 355 }, {  32, 355 }, {  33, 355 },
 {  34, 519 }, {  35, 355 }, {  36, 355 }, {  37, 355 }, {   0,  17 },
 {   0,2760 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,  12 }, {   0,2754 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {  12, 316 }, {  13, 316 }, {   0,   0 },
 {   0,   0 }, {  10, -78 }, {  17, 316 }, {  12,   0 }, {  13,   0 },
 {  20, 316 }, {  21, 316 }, {  22, 316 }, {  23, 316 }, {  24, 316 },
 {  25, 316 }, {  26, 316 }, {  27, 316 }, {  28, 316 }, {  29, 519 },
 {  30, 558 }, {  31, 316 }, {  32, 316 }, {  33, 316 }, {  34, 316 },
 {  35, 316 }, {  36, 316 }, {  37, 316 }, {   0,  17 }, {   0,2721 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12, 277 }, {  13, 277 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17, 277 }, {   0,   0 }, {   0,   0 }, {  20, 277 },

 {  21, 277 }, {  22, 277 }, {  23, 277 }, {  24, 277 }, {  25, 277 },
 {  26, 277 }, {  27, 277 }, {  28, 277 }, {  29, 277 }, {  30, 277 },
 {  31, 277 }, {  32, 277 }, {  33, 277 }, {  34, 277 }, {  35, 277 },
 {  36, 558 }, {  37, 277 }, {   0,  17 }, {   0,2682 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12, 238 }, {  13, 238 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17, 238 }, {   0,   0 }, {   0,   0 }, {  20, 558 }, {  21, 238 },
 {  22, 238 }, {  23, 238 }, {  24, 238 }, {  25, 238 }, {  26, 238 },
 {  27, 238 }, {  28, 238 }, {  29, 238 }, {  30, 238 }, {  31, 238 },

 {  32, 238 }, {  33, 597 }, {  34, 238 }, {  35, 238 }, {  36, 238 },
 {  37, 238 }, {   0,  17 }, {   0,2643 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12, 199 },
 {  13, 199 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17, 199 },
 {   0,   0 }, {   0,   0 }, {  20, 597 }, {  21, 199 }, {  22, 199 },
 {  23, 199 }, {  24, 199 }, {  25, 199 }, {  26, 636 }, {  27, 199 },
 {  28, 199 }, {  29, 199 }, {  30, 199 }, {  31, 199 }, {  32, 199 },
 {  33, 199 }, {  34, 199 }, {  35, 199 }, {  36, 199 }, {  37, 199 },
 {   0,  17 }, {   0,2604 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12, 160 }, {  13, 160 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17, 160 }, {   0,   0 },
 {   0,   0 }, {  20, 160 }, {  21, 636 }, {  22, 160 }, {  23, 675 },
 {  24, 160 }, {  25, 160 }, {  26, 160 }, {  27, 160 }, {  28, 160 },
 {  29, 160 }, {  30, 160 }, {  31, 160 }, {  32, 160 }, {  33, 714 },
 {  34, 160 }, {  35, 160 }, {  36, 160 }, {  37, 160 }, {   0,  17 },
 {   0,2565 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12, 121 }, {  13, 121 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {  17, 121 }, {   0,   0 }, {   0,   0 },
 {  20, 121 }, {  21, 121 }, {  22, 121 }, {  23, 121 }, {  24, 121 },
 {  25, 121 }, {  26, 121 }, {  27, 121 }, {  28, 121 }, {  29, 121 },
 {  30, 121 }, {  31, 121 }, {  32, 121 }, {  33, 121 }, {  34, 714 },
 {  35, 121 }, {  36, 121 }, {  37, 121 }, {   0,   0 }, {   0,2526 },
 {   1, 714 }, {   2, 714 }, {   3, 714 }, {   4, 714 }, {   5, 714 },
 {   6, 714 }, {   7, 714 }, {   8, 755 }, {   9, 714 }, {  10, 714 },
 {  11, 714 }, {  12, 714 }, {  13, 714 }, {  14, 714 }, {  15, 714 },
 {  16, 714 }, {  17, 714 }, {  18, 714 }, {  19, 714 }, {  20, 714 },
 {  21, 714 }, {  22, 714 }, {  23, 714 }, {  24, 714 }, {  25, 714 },

 {  26, 714 }, {  27, 714 }, {  28, 714 }, {  29, 714 }, {  30, 714 },
 {  31, 714 }, {  32, 714 }, {  33, 714 }, {  34, 714 }, {  35, 714 },
 {  36, 714 }, {  37, 714 }, {  38, 714 }, {  39, 714 }, {   0,   0 },
 {   0,2485 }, {   1, 755 }, {   2, 755 }, {   3,  92 }, {   4, 755 },
 {   5, 755 }, {   6, 755 }, {   7, 755 }, {   8, 755 }, {   9, 755 },
 {  10, 755 }, {  11, 755 }, {  12, 755 }, {  13, 755 }, {  14, 755 },
 {  15, 755 }, {  16, 755 }, {  17, 755 }, {  18, 755 }, {  19, 755 },
 {  20, 755 }, {  21, 755 }, {  22, 755 }, {  23, 755 }, {  24, 755 },
 {  25, 755 }, {  26, 755 }, {  27, 755 }, {  28, 755 }, {  29, 755 },
 {  30, 755 }, {  31, 755 }, {  32, 755 }, {  33, 755 }, {  34, 755 },

 {  35, 755 }, {  36, 755 }, {  37, 755 }, {  38, 755 }, {  39, 755 },
 {   0,  17 }, {   0,2444 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,   0 }, {  13,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,   0 }, {   0,   0 },
 {   0,   0 }, {  20,   0 }, {  21,   0 }, {  22,   0 }, {  23,   0 },
 {  24,   0 }, {  25,   0 }, {  26,   0 }, {  27,   0 }, {  28,   0 },
 {  29,   0 }, {  30,   0 }, {  31,   0 }, {  32,   0 }, {  33,   0 },
 {  34,   0 }, {  35,   0 }, {  36,   0 }, {  37,   0 }, {   0,   0 },
 {   0,2405 }, {   0,   0 }, {   2,   0 }, {   0,  22 }, {   0,2401 },

 {   0,   0 }, {   0,2399 }, {   0,  17 }, {   0,2397 }, {   0,  13 },
 {   0,2395 }, {   0,  27 }, {   0,2393 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  19,   4 },
 {  12, -47 }, {  13, -47 }, {  12,   0 }, {  13,   0 }, {   0,   0 },
 {  17, -47 }, {   0,   0 }, {  21,  60 }, {  20, -47 }, {  21, -47 },
 {  22, -47 }, {  23, -47 }, {  24, -47 }, {  25, -47 }, {  26, -47 },
 {  27, -47 }, {  28, -47 }, {  29, -47 }, {  30, 708 }, {  31, -47 },
 {  32, -47 }, {  33, -47 }, {  34, -47 }, {  35, -47 }, {  36, -47 },
 {  37, -47 }, {   0,  17 }, {   0,2358 }, {   0,  13 }, {   0,2356 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12, -86 },
 {  13, -86 }, {  12, -39 }, {  13, -39 }, {   0,   0 }, {  17, -86 },
 {   0,   0 }, {   0,2339 }, {  20, -86 }, {  21, -86 }, {  22, -86 },
 {  23, -86 }, {  24, -86 }, {  25, -86 }, {  26, -86 }, {  27, -86 },
 {  28, 708 }, {  29, -86 }, {  30, -86 }, {  31, -86 }, {  32, -86 },
 {  33, -86 }, {  34, -86 }, {  35, -86 }, {  36, -86 }, {  37, -86 },
 {   0,  11 }, {   0,2319 }, {   0,  28 }, {   0,2317 }, {   0,   0 },
 {   0,2315 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  28,  24 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-125 }, {  13,-125 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-125 }, {   0,   0 },

 {   0,2300 }, {  20,-125 }, {  21,-125 }, {  22,-125 }, {  23,-125 },
 {  24,-125 }, {  25,-125 }, {  26,-125 }, {  27,-125 }, {  28,-125 },
 {  29,-125 }, {  30,-125 }, {  31,-125 }, {  32,-125 }, {  33,-125 },
 {  34,-125 }, {  35,-125 }, {  36,-125 }, {  37,-125 }, {   0,  10 },
 {   0,2280 }, {  36,  15 }, {  22,  39 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-164 }, {  13,-164 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-164 }, {   0,   0 }, {   0,2261 },
 {  20,-164 }, {  21,-164 }, {  22,-164 }, {  23,-164 }, {  24,-164 },
 {  25,-164 }, {  26,-164 }, {  27,-164 }, {  28,-164 }, {  29,-164 },

 {  30,-164 }, {  31,-164 }, {  32,-164 }, {  33,-164 }, {  34,-164 },
 {  35,-164 }, {  36,-164 }, {  37,-164 }, {   0,  17 }, {   0,2241 },
 {   0,   0 }, {   0,2239 }, {  23,  22 }, {   2,   4 }, {   0,   0 },
 {   0,2235 }, {   0,   0 }, {   2,   0 }, {   0,   0 }, {   4,2153 },
 {   0,   0 }, {  12,-203 }, {  13,-203 }, {   0,   0 }, {   0,   0 },
 {   0,2225 }, {  17,-203 }, {   2,  25 }, {   3,  30 }, {  20, 630 },
 {  21,-203 }, {  22,-203 }, {  23,-203 }, {  24,-203 }, {  25,-203 },
 {  26,-203 }, {  27,-203 }, {  28,-203 }, {  29,-203 }, {  30,-203 },
 {  31,-203 }, {  32,-203 }, {  33,-203 }, {  34,-203 }, {  35,-203 },
 {  36,-203 }, {  37,-203 }, {   0,  14 }, {   0,2202 }, {   0,   0 },

 {   0,2200 }, {   0,   0 }, {   2,   0 }, {   3,   5 }, {   0,   5 },
 {   0,2195 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-242 }, {  13,-242 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-242 }, {   0,   0 }, {   0,   0 }, {  20,-242 }, {  21,-242 },
 {  22,-242 }, {  23,-242 }, {  24,-242 }, {  25,-242 }, {  26,-242 },
 {  27,-242 }, {  28,-242 }, {  29,-242 }, {  30,-242 }, {  31,-242 },
 {  32,-242 }, {  33,-242 }, {  34,-242 }, {  35, 630 }, {  36,-242 },
 {  37,-242 }, {   0,  17 }, {   0,2163 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-281 },

 {  13,-281 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-281 },
 {   0,   0 }, {   0,   0 }, {  20,-281 }, {  21,-281 }, {  22,-281 },
 {  23,-281 }, {  24,-281 }, {  25,-281 }, {  26,-281 }, {  27,-281 },
 {  28,-281 }, {  29,-281 }, {  30,-281 }, {  31,-281 }, {  32,-281 },
 {  33,-281 }, {  34,-281 }, {  35, 630 }, {  36,-281 }, {  37,-281 },
 {   0,  17 }, {   0,2124 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-320 }, {  13,-320 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-320 }, {   0,   0 },
 {   0,   0 }, {  20,-320 }, {  21,-320 }, {  22,-320 }, {  23,-320 },

 {  24,-320 }, {  25,-320 }, {  26,-320 }, {  27,-320 }, {  28,-320 },
 {  29,-320 }, {  30,-320 }, {  31,-320 }, {  32,-320 }, {  33,-320 },
 {  34,-320 }, {  35, 630 }, {  36,-320 }, {  37,-320 }, {   0,  17 },
 {   0,2085 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-359 }, {  13,-359 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-359 }, {   0,   0 }, {   0,   0 },
 {  20,-359 }, {  21,-359 }, {  22,-359 }, {  23,-359 }, {  24,-359 },
 {  25,-359 }, {  26,-359 }, {  27,-359 }, {  28,-359 }, {  29,-359 },
 {  30,-359 }, {  31, 630 }, {  32,-359 }, {  33,-359 }, {  34,-359 },

 {  35,-359 }, {  36,-359 }, {  37,-359 }, {   0,  17 }, {   0,2046 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-398 }, {  13,-398 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-398 }, {   0,   0 }, {   0,   0 }, {  20,-398 },
 {  21,-398 }, {  22,-398 }, {  23,-398 }, {  24,-398 }, {  25,-398 },
 {  26,-398 }, {  27,-398 }, {  28,-398 }, {  29, 630 }, {  30,-398 },
 {  31,-398 }, {  32,-398 }, {  33,-398 }, {  34,-398 }, {  35,-398 },
 {  36,-398 }, {  37,-398 }, {   0,  17 }, {   0,2007 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-437 }, {  13,-437 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-437 }, {   0,   0 }, {   0,   0 }, {  20, 630 }, {  21,-437 },
 {  22,-437 }, {  23,-437 }, {  24,-437 }, {  25,-437 }, {  26,-437 },
 {  27,-437 }, {  28,-437 }, {  29,-437 }, {  30,-437 }, {  31,-437 },
 {  32,-437 }, {  33,-437 }, {  34,-437 }, {  35,-437 }, {  36,-437 },
 {  37,-437 }, {   0,   8 }, {   0,1968 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-476 },
 {  13,-476 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-476 },

 {   0,   0 }, {   0,   0 }, {  20,-476 }, {  21,-476 }, {  22,-476 },
 {  23,-476 }, {  24,-476 }, {  25,-476 }, {  26,-476 }, {  27,-476 },
 {  28,-476 }, {  29,-476 }, {  30,-476 }, {  31,-476 }, {  32,-476 },
 {  33,-476 }, {  34,-476 }, {  35,-476 }, {  36,-476 }, {  37,-476 },
 {   0,   9 }, {   0,1929 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-515 }, {  13,-515 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-515 }, {   0,   0 },
 {   0,   0 }, {  20,-515 }, {  21,-515 }, {  22,-515 }, {  23,-515 },
 {  24,-515 }, {  25,-515 }, {  26,-515 }, {  27,-515 }, {  28,-515 },

 {  29,-515 }, {  30,-515 }, {  31,-515 }, {  32,-515 }, {  33,-515 },
 {  34,-515 }, {  35,-515 }, {  36,-515 }, {  37,-515 }, {   0,  17 },
 {   0,1890 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-554 }, {  13,-554 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-554 }, {   0,   0 }, {   0,   0 },
 {  20,-554 }, {  21,-554 }, {  22,-554 }, {  23,-554 }, {  24,-554 },
 {  25,-554 }, {  26,-554 }, {  27,-554 }, {  28,-554 }, {  29,-554 },
 {  30,-554 }, {  31,-554 }, {  32,-554 }, {  33,-554 }, {  34,-554 },
 {  35,-554 }, {  36, 552 }, {  37,-554 }, {   0,   7 }, {   0,1851 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-593 }, {  13,-593 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-593 }, {   0,   0 }, {   0,   0 }, {  20,-593 },
 {  21,-593 }, {  22,-593 }, {  23,-593 }, {  24,-593 }, {  25,-593 },
 {  26,-593 }, {  27,-593 }, {  28,-593 }, {  29,-593 }, {  30,-593 },
 {  31,-593 }, {  32,-593 }, {  33,-593 }, {  34,-593 }, {  35,-593 },
 {  36,-593 }, {  37,-593 }, {   0,   0 }, {   0,1812 }, {   1,   0 },
 {   2,   0 }, {   3,   0 }, {   4,   0 }, {   5,   0 }, {   6,   0 },
 {   7,   0 }, {   8,  41 }, {   9,   0 }, {  10,   0 }, {  11,   0 },

 {  12,   0 }, {  13,   0 }, {  14,   0 }, {  15,   0 }, {  16,   0 },
 {  17,   0 }, {  18,   0 }, {  19,   0 }, {  20,   0 }, {  21,   0 },
 {  22,   0 }, {  23,   0 }, {  24,   0 }, {  25,   0 }, {  26,   0 },
 {  27,   0 }, {  28,   0 }, {  29,   0 }, {  30,   0 }, {  31,   0 },
 {  32,   0 }, {  33,   0 }, {  34,   0 }, {  35,   0 }, {  36,   0 },
 {  37,   0 }, {  38,   0 }, {  39,   0 }, {   0,   0 }, {   0,1771 },
 {   1, 472 }, {   2, 472 }, {   3, 472 }, {   4, 472 }, {   5, 472 },
 {   6, 472 }, {   7, 472 }, {   8, 513 }, {   9, 472 }, {  10, 472 },
 {  11,-546 }, {  12, 472 }, {  13, 472 }, {  14, 472 }, {  15, 472 },
 {  16, 472 }, {  17, 472 }, {  18, 472 }, {  19, 472 }, {  20, 472 },

 {  21, 472 }, {  22, 472 }, {  23, 472 }, {  24, 472 }, {  25, 472 },
 {  26, 472 }, {  27, 472 }, {  28, 472 }, {  29, 472 }, {  30, 472 },
 {  31, 472 }, {  32, 472 }, {  33, 472 }, {  34, 472 }, {  35, 472 },
 {  36, 472 }, {  37, 472 }, {  38, 472 }, {  39, 472 }, {   0,   0 },
 {   0,1730 }, {   1,   0 }, {   2,   0 }, {   3,-663 }, {   4,   0 },
 {   5,   0 }, {   6,   0 }, {   7,   0 }, {   8,   0 }, {   9,   0 },
 {  10,   0 }, {  11,   0 }, {  12,   0 }, {  13,   0 }, {  14,   0 },
 {  15,   0 }, {  16,   0 }, {  17,   0 }, {  18,   0 }, {  19,   0 },
 {  20,   0 }, {  21,   0 }, {  22,   0 }, {  23,   0 }, {  24,   0 },
 {  25,   0 }, {  26,   0 }, {  27,   0 }, {  28,   0 }, {  29,   0 },

 {  30,   0 }, {  31,   0 }, {  32,   0 }, {  33,   0 }, {  34,   0 },
 {  35,   0 }, {  36,   0 }, {  37,   0 }, {  38,   0 }, {  39,   0 },
 {   0,  17 }, {   0,1689 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-755 }, {  13,-755 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-755 }, {   0,   0 },
 {   0,   0 }, {  20,-755 }, {  21,-755 }, {  22,-755 }, {  23,-755 },
 {  24,-755 }, {  25,-755 }, {  26,-755 }, {  27,-755 }, {  28,-755 },
 {  29,-755 }, {  30,-755 }, {  31,-755 }, {  32,-755 }, {  33,-755 },
 {  34,-755 }, {  35, 472 }, {  36,-755 }, {  37,-755 }, {   0,  17 },

 {   0,1650 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-794 }, {  13,-794 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-794 }, {   0,   0 }, {   0,   0 },
 {  20,-794 }, {  21,-794 }, {  22,-794 }, {  23,-794 }, {  24,-794 },
 {  25,-794 }, {  26,-794 }, {  27,-794 }, {  28,-794 }, {  29,-794 },
 {  30,-794 }, {  31,-794 }, {  32,-794 }, {  33,-794 }, {  34, 472 },
 {  35,-794 }, {  36,-794 }, {  37,-794 }, {   0,  17 }, {   0,1611 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {  12,-833 }, {  13,-833 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-833 }, {   0,   0 }, {   0,   0 }, {  20,-833 },
 {  21,-833 }, {  22,-833 }, {  23,-833 }, {  24,-833 }, {  25, 472 },
 {  26,-833 }, {  27,-833 }, {  28,-833 }, {  29,-833 }, {  30,-833 },
 {  31,-833 }, {  32,-833 }, {  33,-833 }, {  34,-833 }, {  35,-833 },
 {  36,-833 }, {  37,-833 }, {   0,  17 }, {   0,1572 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-872 }, {  13,-872 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-872 }, {   0,   0 }, {   0,   0 }, {  20,-872 }, {  21,-872 },

 {  22,-872 }, {  23, 472 }, {  24,-872 }, {  25,-872 }, {  26,-872 },
 {  27,-872 }, {  28,-872 }, {  29,-872 }, {  30,-872 }, {  31,-872 },
 {  32,-872 }, {  33,-872 }, {  34,-872 }, {  35,-872 }, {  36,-872 },
 {  37,-872 }, {   0,  14 }, {   0,1533 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-911 },
 {  13,-911 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-911 },
 {   0,   0 }, {   0,   0 }, {  20,-911 }, {  21,-911 }, {  22,-911 },
 {  23,-911 }, {  24,-911 }, {  25,-911 }, {  26,-911 }, {  27,-911 },
 {  28,-911 }, {  29,-911 }, {  30,-911 }, {  31,-911 }, {  32,-911 },

 {  33,-911 }, {  34,-911 }, {  35,-911 }, {  36,-911 }, {  37,-911 },
 {   0,  17 }, {   0,1494 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-950 }, {  13,-950 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-950 }, {   0,   0 },
 {   0,   0 }, {  20,-950 }, {  21, 433 }, {  22,-950 }, {  23,-950 },
 {  24,-950 }, {  25,-950 }, {  26,-950 }, {  27,-950 }, {  28,-950 },
 {  29,-950 }, {  30,-950 }, {  31,-950 }, {  32,-950 }, {  33,-950 },
 {  34,-950 }, {  35,-950 }, {  36,-950 }, {  37,-950 }, {   0,  17 },
 {   0,1455 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-989 }, {  13,-989 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-989 }, {   0,   0 }, {   0,   0 },
 {  20,-989 }, {  21,-989 }, {  22,-989 }, {  23,-989 }, {  24,-989 },
 {  25, 433 }, {  26,-989 }, {  27,-989 }, {  28,-989 }, {  29,-989 },
 {  30,-989 }, {  31,-989 }, {  32,-989 }, {  33,-989 }, {  34,-989 },
 {  35,-989 }, {  36,-989 }, {  37,-989 }, {   0,  17 }, {   0,1416 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-1028 }, {  13,-1028 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {  17,-1028 }, {   0,   0 }, {   0,   0 }, {  20,-1028 },
 {  21,-1028 }, {  22,-1028 }, {  23,-1028 }, {  24,-1028 }, {  25,-1028 },
 {  26,-1028 }, {  27,-1028 }, {  28,-1028 }, {  29,-1028 }, {  30,-1028 },
 {  31,-1028 }, {  32, 433 }, {  33,-1028 }, {  34,-1028 }, {  35,-1028 },
 {  36,-1028 }, {  37,-1028 }, {   0,  17 }, {   0,1377 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-1067 }, {  13,-1067 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-1067 }, {   0,   0 }, {   0,   0 }, {  20,-1067 }, {  21,-1067 },
 {  22, 433 }, {  23,-1067 }, {  24,-1067 }, {  25,-1067 }, {  26,-1067 },

 {  27,-1067 }, {  28,-1067 }, {  29,-1067 }, {  30,-1067 }, {  31,-1067 },
 {  32,-1067 }, {  33,-1067 }, {  34,-1067 }, {  35,-1067 }, {  36,-1067 },
 {  37,-1067 }, {   0,  17 }, {   0,1338 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1106 },
 {  13,-1106 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1106 },
 {   0,   0 }, {   0,   0 }, {  20,-1106 }, {  21,-1106 }, {  22,-1106 },
 {  23, 433 }, {  24,-1106 }, {  25,-1106 }, {  26,-1106 }, {  27,-1106 },
 {  28,-1106 }, {  29,-1106 }, {  30,-1106 }, {  31,-1106 }, {  32,-1106 },
 {  33,-1106 }, {  34,-1106 }, {  35,-1106 }, {  36,-1106 }, {  37,-1106 },

 {   0,   0 }, {   0,1299 }, {   1, 433 }, {   2, 433 }, {   3, 433 },
 {   4, 433 }, {   5, 433 }, {   6, 433 }, {   7, 433 }, {   8,  41 },
 {   9, 433 }, {  10, 433 }, {  11, 474 }, {  12, 433 }, {  13, 433 },
 {  14, 433 }, {  15, 433 }, {  16, 433 }, {  17, 433 }, {  18, 433 },
 {  19, 433 }, {  20, 433 }, {  21, 433 }, {  22, 433 }, {  23, 433 },
 {  24, 433 }, {  25, 433 }, {  26, 433 }, {  27, 433 }, {  28, 433 },
 {  29, 433 }, {  30, 433 }, {  31, 433 }, {  32, 433 }, {  33, 433 },
 {  34, 433 }, {  35, 433 }, {  36, 433 }, {  37, 433 }, {  38, 433 },
 {  39, 433 }, {   0,   0 }, {   0,1258 }, {   1, -41 }, {   2, -41 },
 {   3, -41 }, {   4, -41 }, {   5, -41 }, {   6, -41 }, {   7, -41 },

 {   8,   0 }, {   9, -41 }, {  10, -41 }, {  11,-1059 }, {  12, -41 },
 {  13, -41 }, {  14, -41 }, {  15, -41 }, {  16, -41 }, {  17, -41 },
 {  18, -41 }, {  19, -41 }, {  20, -41 }, {  21, -41 }, {  22, -41 },
 {  23, -41 }, {  24, -41 }, {  25, -41 }, {  26, -41 }, {  27, -41 },
 {  28, -41 }, {  29, -41 }, {  30, -41 }, {  31, -41 }, {  32, -41 },
 {  33, -41 }, {  34, -41 }, {  35, -41 }, {  36, -41 }, {  37, -41 },
 {  38, -41 }, {  39, -41 }, {   0,  17 }, {   0,1217 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-1227 }, {  13,-1227 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {  17,-1227 }, {   0,   0 }, {   0,   0 }, {  20,-1227 }, {  21,-1227 },
 {  22,-1227 }, {  23,-1227 }, {  24,-1227 }, {  25,-1227 }, {  26,-1227 },
 {  27,-1227 }, {  28,-1227 }, {  29,-1227 }, {  30,-1227 }, {  31,-1227 },
 {  32,-1227 }, {  33, 433 }, {  34,-1227 }, {  35,-1227 }, {  36,-1227 },
 {  37,-1227 }, {   0,  17 }, {   0,1178 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1266 },
 {  13,-1266 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1266 },
 {   0,   0 }, {   0,   0 }, {  20,-1266 }, {  21,-1266 }, {  22,-1266 },
 {  23, 433 }, {  24,-1266 }, {  25,-1266 }, {  26,-1266 }, {  27,-1266 },

 {  28,-1266 }, {  29,-1266 }, {  30,-1266 }, {  31,-1266 }, {  32,-1266 },
 {  33,-1266 }, {  34,-1266 }, {  35,-1266 }, {  36,-1266 }, {  37,-1266 },
 {   0,  17 }, {   0,1139 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1305 }, {  13,-1305 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1305 }, {   0,   0 },
 {   0,   0 }, {  20,-1305 }, {  21,-1305 }, {  22,-1305 }, {  23, 433 },
 {  24,-1305 }, {  25,-1305 }, {  26,-1305 }, {  27,-1305 }, {  28,-1305 },
 {  29,-1305 }, {  30,-1305 }, {  31,-1305 }, {  32,-1305 }, {  33,-1305 },
 {  34,-1305 }, {  35,-1305 }, {  36,-1305 }, {  37,-1305 }, {   0,  17 },

 {   0,1100 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-1344 }, {  13,-1344 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-1344 }, {   0,   0 }, {   0,   0 },
 {  20,-1344 }, {  21,-1344 }, {  22,-1344 }, {  23,-1344 }, {  24,-1344 },
 {  25,-1344 }, {  26,-1344 }, {  27,-1344 }, {  28,-1344 }, {  29,-1344 },
 {  30,-1344 }, {  31,-1344 }, {  32,-1344 }, {  33, 433 }, {  34,-1344 },
 {  35,-1344 }, {  36,-1344 }, {  37,-1344 }, {   0,  17 }, {   0,1061 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {  12,-1383 }, {  13,-1383 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-1383 }, {   0,   0 }, {   0,   0 }, {  20,-1383 },
 {  21,-1383 }, {  22,-1383 }, {  23,-1383 }, {  24,-1383 }, {  25,-1383 },
 {  26, 433 }, {  27,-1383 }, {  28,-1383 }, {  29,-1383 }, {  30,-1383 },
 {  31,-1383 }, {  32,-1383 }, {  33,-1383 }, {  34,-1383 }, {  35,-1383 },
 {  36,-1383 }, {  37,-1383 }, {   0,  17 }, {   0,1022 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-1422 }, {  13,-1422 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-1422 }, {   0,   0 }, {   0,   0 }, {  20,-1422 }, {  21,-1422 },

 {  22,-1422 }, {  23,-1422 }, {  24,-1422 }, {  25,-1422 }, {  26,-1422 },
 {  27,-1422 }, {  28,-1422 }, {  29,-1422 }, {  30,-1422 }, {  31,-1422 },
 {  32,-1422 }, {  33, 433 }, {  34,-1422 }, {  35,-1422 }, {  36,-1422 },
 {  37,-1422 }, {   0,  17 }, {   0, 983 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1461 },
 {  13,-1461 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1461 },
 {   0,   0 }, {   0,   0 }, {  20,-1461 }, {  21,-1461 }, {  22,-1461 },
 {  23,-1461 }, {  24,-1461 }, {  25,-1461 }, {  26,-1461 }, {  27,-1461 },
 {  28, 433 }, {  29,-1461 }, {  30,-1461 }, {  31,-1461 }, {  32,-1461 },

 {  33,-1461 }, {  34,-1461 }, {  35,-1461 }, {  36,-1461 }, {  37,-1461 },
 {   0,  17 }, {   0, 944 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1500 }, {  13,-1500 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1500 }, {   0,   0 },
 {   0,   0 }, {  20,-1500 }, {  21,-1500 }, {  22,-1500 }, {  23, 433 },
 {  24,-1500 }, {  25,-1500 }, {  26,-1500 }, {  27,-1500 }, {  28,-1500 },
 {  29,-1500 }, {  30,-1500 }, {  31,-1500 }, {  32,-1500 }, {  33,-1500 },
 {  34,-1500 }, {  35,-1500 }, {  36,-1500 }, {  37,-1500 }, {   0,  15 },
 {   0, 905 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-1539 }, {  13,-1539 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-1539 }, {   0,   0 }, {   0,   0 },
 {  20,-1539 }, {  21,-1539 }, {  22,-1539 }, {  23,-1539 }, {  24,-1539 },
 {  25,-1539 }, {  26,-1539 }, {  27,-1539 }, {  28,-1539 }, {  29,-1539 },
 {  30,-1539 }, {  31,-1539 }, {  32,-1539 }, {  33,-1539 }, {  34,-1539 },
 {  35,-1539 }, {  36,-1539 }, {  37,-1539 }, {   0,   0 }, {   0, 866 },
 {   1,   0 }, {   2,   0 }, {   3,   0 }, {   4,   0 }, {   5,   0 },
 {   6,   0 }, {   7,   0 }, {   8,-392 }, {   9,   0 }, {  10,   0 },
 {  11,  41 }, {  12,   0 }, {  13,   0 }, {  14,   0 }, {  15,   0 },

 {  16,   0 }, {  17,   0 }, {  18,   0 }, {  19,   0 }, {  20,   0 },
 {  21,   0 }, {  22,   0 }, {  23,   0 }, {  24,   0 }, {  25,   0 },
 {  26,   0 }, {  27,   0 }, {  28,   0 }, {  29,   0 }, {  30,   0 },
 {  31,   0 }, {  32,   0 }, {  33,   0 }, {  34,   0 }, {  35,   0 },
 {  36,   0 }, {  37,   0 }, {  38,   0 }, {  39,   0 }, {   0,   0 },
 {   0, 825 }, {   1, -41 }, {   2, -41 }, {   3, -41 }, {   4, -41 },
 {   5, -41 }, {   6, -41 }, {   7, -41 }, {   8,-433 }, {   9, -41 },
 {  10, -41 }, {  11,   0 }, {  12, -41 }, {  13, -41 }, {  14, -41 },
 {  15, -41 }, {  16, -41 }, {  17, -41 }, {  18, -41 }, {  19, -41 },
 {  20, -41 }, {  21, -41 }, {  22, -41 }, {  23, -41 }, {  24, -41 },

 {  25, -41 }, {  26, -41 }, {  27, -41 }, {  28, -41 }, {  29, -41 },
 {  30, -41 }, {  31, -41 }, {  32, -41 }, {  33, -41 }, {  34, -41 },
 {  35, -41 }, {  36, -41 }, {  37, -41 }, {  38, -41 }, {  39, -41 },
 {   0,  17 }, {   0, 784 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1660 }, {  13,-1660 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1660 }, {   0,   0 },
 {   0,   0 }, {  20,-1660 }, {  21,-1660 }, {  22,-1660 }, {  23,-1660 },
 {  24,-1660 }, {  25,-1660 }, {  26,-1660 }, {  27,-1660 }, {  28,-1660 },
 {  29,-1660 }, {  30,-1660 }, {  31, 312 }, {  32,-1660 }, {  33,-1660 },

 {  34,-1660 }, {  35,-1660 }, {  36,-1660 }, {  37,-1660 }, {   0,  16 },
 {   0, 745 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-1699 }, {  13,-1699 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-1699 }, {   0,   0 }, {   0,   0 },
 {  20,-1699 }, {  21,-1699 }, {  22,-1699 }, {  23,-1699 }, {  24,-1699 },
 {  25,-1699 }, {  26,-1699 }, {  27,-1699 }, {  28,-1699 }, {  29,-1699 },
 {  30,-1699 }, {  31,-1699 }, {  32,-1699 }, {  33,-1699 }, {  34,-1699 },
 {  35,-1699 }, {  36,-1699 }, {  37,-1699 }, {   0,   4 }, {   0, 706 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-1738 }, {  13,-1738 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-1738 }, {   0,   0 }, {   0,   0 }, {  20,-1738 },
 {  21,-1738 }, {  22,-1738 }, {  23,-1738 }, {  24,-1738 }, {  25,-1738 },
 {  26,-1738 }, {  27,-1738 }, {  28,-1738 }, {  29,-1738 }, {  30,-1738 },
 {  31,-1738 }, {  32,-1738 }, {  33,-1738 }, {  34,-1738 }, {  35,-1738 },
 {  36,-1738 }, {  37,-1738 }, {   0,  17 }, {   0, 667 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-1777 }, {  13,-1777 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {  17,-1777 }, {   0,   0 }, {   0,   0 }, {  20,-1777 }, {  21,-1777 },
 {  22,-1777 }, {  23,-1777 }, {  24, 234 }, {  25,-1777 }, {  26,-1777 },
 {  27,-1777 }, {  28,-1777 }, {  29,-1777 }, {  30,-1777 }, {  31,-1777 },
 {  32,-1777 }, {  33,-1777 }, {  34,-1777 }, {  35,-1777 }, {  36,-1777 },
 {  37,-1777 }, {   0,   6 }, {   0, 628 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1816 },
 {  13,-1816 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1816 },
 {   0,   0 }, {   0,   0 }, {  20,-1816 }, {  21,-1816 }, {  22,-1816 },
 {  23,-1816 }, {  24,-1816 }, {  25,-1816 }, {  26,-1816 }, {  27,-1816 },

 {  28,-1816 }, {  29,-1816 }, {  30,-1816 }, {  31,-1816 }, {  32,-1816 },
 {  33,-1816 }, {  34,-1816 }, {  35,-1816 }, {  36,-1816 }, {  37,-1816 },
 {   0,  17 }, {   0, 589 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-1855 }, {  13,-1855 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-1855 }, {   0,   0 },
 {   0,   0 }, {  20, 195 }, {  21,-1855 }, {  22,-1855 }, {  23,-1855 },
 {  24,-1855 }, {  25,-1855 }, {  26,-1855 }, {  27,-1855 }, {  28,-1855 },
 {  29,-1855 }, {  30,-1855 }, {  31,-1855 }, {  32,-1855 }, {  33,-1855 },
 {  34,-1855 }, {  35,-1855 }, {  36,-1855 }, {  37,-1855 }, {   0,  17 },

 {   0, 550 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-1894 }, {  13,-1894 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-1894 }, {   0,   0 }, {   0,   0 },
 {  20,-1894 }, {  21,-1894 }, {  22,-1894 }, {  23, 195 }, {  24,-1894 },
 {  25,-1894 }, {  26,-1894 }, {  27,-1894 }, {  28,-1894 }, {  29,-1894 },
 {  30,-1894 }, {  31,-1894 }, {  32,-1894 }, {  33,-1894 }, {  34,-1894 },
 {  35,-1894 }, {  36,-1894 }, {  37,-1894 }, {   0,  17 }, {   0, 511 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {  12,-1933 }, {  13,-1933 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-1933 }, {   0,   0 }, {   0,   0 }, {  20,-1933 },
 {  21,-1933 }, {  22,-1933 }, {  23,-1933 }, {  24,-1933 }, {  25,-1933 },
 {  26,-1933 }, {  27,-1933 }, {  28,-1933 }, {  29,-1933 }, {  30,-1933 },
 {  31,-1933 }, {  32,-1933 }, {  33, 195 }, {  34,-1933 }, {  35,-1933 },
 {  36,-1933 }, {  37,-1933 }, {   0,  17 }, {   0, 472 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-1972 }, {  13,-1972 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-1972 }, {   0,   0 }, {   0,   0 }, {  20,-1972 }, {  21,-1972 },

 {  22,-1972 }, {  23,-1972 }, {  24,-1972 }, {  25,-1972 }, {  26,-1972 },
 {  27, 195 }, {  28,-1972 }, {  29,-1972 }, {  30,-1972 }, {  31,-1972 },
 {  32,-1972 }, {  33,-1972 }, {  34,-1972 }, {  35,-1972 }, {  36,-1972 },
 {  37,-1972 }, {   0,  17 }, {   0, 433 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-2011 },
 {  13,-2011 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-2011 },
 {   0,   0 }, {   0,   0 }, {  20, 195 }, {  21,-2011 }, {  22,-2011 },
 {  23,-2011 }, {  24,-2011 }, {  25,-2011 }, {  26,-2011 }, {  27,-2011 },
 {  28,-2011 }, {  29,-2011 }, {  30,-2011 }, {  31,-2011 }, {  32,-2011 },

 {  33,-2011 }, {  34,-2011 }, {  35,-2011 }, {  36,-2011 }, {  37,-2011 },
 {   0,  17 }, {   0, 394 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-2050 }, {  13,-2050 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-2050 }, {   0,   0 },
 {   0,   0 }, {  20,-2050 }, {  21,-2050 }, {  22,-2050 }, {  23,-2050 },
 {  24,-2050 }, {  25,-2050 }, {  26,-2050 }, {  27,-2050 }, {  28,-2050 },
 {  29, 195 }, {  30,-2050 }, {  31,-2050 }, {  32,-2050 }, {  33,-2050 },
 {  34,-2050 }, {  35,-2050 }, {  36,-2050 }, {  37,-2050 }, {   0,  17 },
 {   0, 355 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  12,-2089 }, {  13,-2089 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-2089 }, {   0,   0 }, {   0,   0 },
 {  20,-2089 }, {  21,-2089 }, {  22,-2089 }, {  23,-2089 }, {  24,-2089 },
 {  25,-2089 }, {  26,-2089 }, {  27,-2089 }, {  28,-2089 }, {  29,-2089 },
 {  30,-2089 }, {  31,-2089 }, {  32,-2089 }, {  33,-351 }, {  34,-2089 },
 {  35,-2089 }, {  36,-2089 }, {  37,-2089 }, {   0,   2 }, {   0, 316 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-2128 }, {  13,-2128 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {  17,-2128 }, {   0,   0 }, {   0,   0 }, {  20,-2128 },
 {  21,-2128 }, {  22,-2128 }, {  23,-2128 }, {  24,-2128 }, {  25,-2128 },
 {  26,-2128 }, {  27,-2128 }, {  28,-2128 }, {  29,-2128 }, {  30,-2128 },
 {  31,-2128 }, {  32,-2128 }, {  33,-2128 }, {  34,-2128 }, {  35,-2128 },
 {  36,-2128 }, {  37,-2128 }, {   0,  17 }, {   0, 277 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  12,-2167 }, {  13,-2167 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {  17,-2167 }, {   0,   0 }, {   0,   0 }, {  20,-2167 }, {  21,-2167 },
 {  22,-351 }, {  23,-2167 }, {  24,-2167 }, {  25,-2167 }, {  26,-2167 },

 {  27,-2167 }, {  28,-2167 }, {  29,-2167 }, {  30,-2167 }, {  31,-2167 },
 {  32,-2167 }, {  33,-2167 }, {  34,-2167 }, {  35,-2167 }, {  36,-2167 },
 {  37,-2167 }, {   0,  17 }, {   0, 238 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-2206 },
 {  13,-2206 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-2206 },
 {   0,   0 }, {   0,   0 }, {  20,-2206 }, {  21,  78 }, {  22,-2206 },
 {  23,-2206 }, {  24,-2206 }, {  25,-2206 }, {  26,-2206 }, {  27,-2206 },
 {  28,-2206 }, {  29,-2206 }, {  30,-2206 }, {  31,-2206 }, {  32,-2206 },
 {  33,-2206 }, {  34,-2206 }, {  35,-2206 }, {  36,-2206 }, {  37,-2206 },

 {   0,   1 }, {   0, 199 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  12,-2245 }, {  13,-2245 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  17,-2245 }, {   0,   0 },
 {   0,   0 }, {  20,-2245 }, {  21,-2245 }, {  22,-2245 }, {  23,-2245 },
 {  24,-2245 }, {  25,-2245 }, {  26,-2245 }, {  27,-2245 }, {  28,-2245 },
 {  29,-2245 }, {  30,-2245 }, {  31,-2245 }, {  32,-2245 }, {  33,-2245 },
 {  34,-2245 }, {  35,-2245 }, {  36,-2245 }, {  37,-2245 }, {   0,  17 },
 {   0, 160 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {  12,-2284 }, {  13,-2284 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  17,-2284 }, {   0,   0 }, {   0,   0 },
 {  20,-2284 }, {  21,-2284 }, {  22,-2284 }, {  23,  39 }, {  24,-2284 },
 {  25,-2284 }, {  26,-2284 }, {  27,-2284 }, {  28,-2284 }, {  29,-2284 },
 {  30,-2284 }, {  31,-2284 }, {  32,-2284 }, {  33,-2284 }, {  34,-2284 },
 {  35,-2284 }, {  36,-2284 }, {  37,-2284 }, {   0,   3 }, {   0, 121 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  12,-2323 }, {  13,-2323 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  17,-2323 }, {   0,   0 }, {   0,   0 }, {  20,-2323 },

 {  21,-2323 }, {  22,-2323 }, {  23,-2323 }, {  24,-2323 }, {  25,-2323 },
 {  26,-2323 }, {  27,-2323 }, {  28,-2323 }, {  29,-2323 }, {  30,-2323 },
 {  31,-2323 }, {  32,-2323 }, {  33,-2323 }, {  34,-2323 }, {  35,-2323 },
 {  36,-2323 }, {  37,-2323 }, {   0,   0 }, {   0,  82 }, {   1,  41 },
 {   2,  41 }, {   0,   0 }, {   4,-2143 }, {   5,  41 }, {   6,  41 },
 {   7,  41 }, {   8,  41 }, {   9,  41 }, {  10,  41 }, {  11,  41 },
 {  12,  41 }, {  13,  41 }, {  14,  41 }, {  15,  41 }, {  16,  41 },
 {  17,  41 }, {  18,  41 }, {  19,  41 }, {  20,  41 }, {  21,  41 },
 {  22,  41 }, {  23,  41 }, {  24,  41 }, {  25,  41 }, {  26,  41 },
 {  27,  41 }, {  28,  41 }, {  29,  41 }, {  30,  41 }, {  31,  41 },

 {  32,  41 }, {  33,  41 }, {  34,  41 }, {  35,  41 }, {  36,  41 },
 {  37,  41 }, {  38,  41 }, {  39,  41 }, {   0,   0 }, {   0,  41 },
 {   1,   0 }, {   2,   0 }, {   0,   0 }, {   4,-2184 }, {   5,   0 },
 {   6,   0 }, {   7,   0 }, {   8,   0 }, {   9,   0 }, {  10,   0 },
 {  11,   0 }, {  12,   0 }, {  13,   0 }, {  14,   0 }, {  15,   0 },
 {  16,   0 }, {  17,   0 }, {  18,   0 }, {  19,   0 }, {  20,   0 },
 {  21,   0 }, {  22,   0 }, {  23,   0 }, {  24,   0 }, {  25,   0 },
 {  26,   0 }, {  27,   0 }, {  28,   0 }, {  29,   0 }, {  30,   0 },
 {  31,   0 }, {  32,   0 }, {  33,   0 }, {  34,   0 }, {  35,   0 },
 {  36,   0 }, {  37,   0 }, {  38,   0 }, {  39,   0 }, {  40,  32 },

 {   1,   0 },    };

static yyconst struct yy_trans_info *yy_start_state_list[3] =
    {
    &yy_transition[1],
    &yy_transition[3],
    &yy_transition[44],

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    8,    1,    9,    1,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    1,
       16,    1,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,    1,   19,    1,    1,    1,   20,   17,   21,   22,

       23,   24,   25,   26,   27,   17,   17,   28,   29,   30,
       31,   32,   17,   33,   34,   35,   36,   37,   17,   17,
       17,   17,   38,    1,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[32] =
    {   0,
0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int glfx_flex_debug;
int glfx_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *glfxtext;
#line 1 "glfx.lpp"
#line 9 "glfx.lpp"
    //#define DEBUG_PRINT

    #ifdef _MSC_VER
    // MS's C++ compiler is more strict than gcc

    // No unistd.h
    #define YY_NO_UNISTD_H

    // Direct IO functions (read and such)
    #include <io.h>

    // Disable the warning for glfxwrap
    #pragma warning( disable: 4003 )

    // Disable the warning about depracted naming of _read and friends
    #pragma warning( disable: 4996 )

    #endif

    #ifdef _M_X64
    // flex is incompatible with x64
    // it makes some casts from pointers to integers and from size_t to integers
    // it should work though, nothing too serious
    #pragma warning( disable:4267 )
    #pragma warning( disable:4244 )
    #endif

    #include <iostream>
    #include <string>
    #include <sstream>

    #include "glfxParser.h"
    #include "glfxClasses.h"

    // tokens from parser generator
    #include "glfxLALRParser.hpp"

    static void debugPrint(const char* name);
    static void errLex(const char* tok);

    using namespace std;
    using namespace glfxParser;
#line 1194 "glfxScanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int glfxlex_destroy (void );

int glfxget_debug (void );

void glfxset_debug (int debug_flag  );

YY_EXTRA_TYPE glfxget_extra (void );

void glfxset_extra (YY_EXTRA_TYPE user_defined  );

FILE *glfxget_in (void );

void glfxset_in  (FILE * in_str  );

FILE *glfxget_out (void );

void glfxset_out  (FILE * out_str  );

int glfxget_leng (void );

char *glfxget_text (void );

int glfxget_lineno (void );

void glfxset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int glfxwrap (void );
#else
extern int glfxwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( glfxtext, glfxleng, 1, glfxout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	errno=0; \
	while ( (result = read( fileno(glfxin), (char *) buf, max_size )) < 0 ) \
	{ \
		if( errno != EINTR) \
		{ \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
			break; \
		} \
		errno=0; \
		clearerr(glfxin); \
	}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int glfxlex (void);

#define YY_DECL int glfxlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after glfxtext and glfxleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 58 "glfx.lpp"

#line 1367 "glfxScanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! glfxin )
			glfxin = stdin;

		if ( ! glfxout )
			glfxout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			glfxensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				glfx_create_buffer(glfxin,YY_BUF_SIZE );
		}

		glfx_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of glfxtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start_state_list[(yy_start)];
yy_match:
		{
		register yyconst struct yy_trans_info *yy_trans_info;

		register YY_CHAR yy_c;

		for ( yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
		      (yy_trans_info = &yy_current_state[(unsigned int) yy_c])->
		yy_verify == yy_c;
		      yy_c = yy_ec[YY_SC_TO_UI(*++yy_cp)]  )
			{
			yy_current_state += yy_trans_info->yy_nxt;

			if ( yy_current_state[-1].yy_nxt )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			}
		}

yy_find_action:
		yy_act = yy_current_state[-1].yy_nxt;

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < glfxleng; ++yyl )
				if ( glfxtext[yyl] == '\n' )
					   
    glfxlineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos) + 1;
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 59 "glfx.lpp"
debugPrint("program"); glfxlval.lineno=glfxlineno; return PROGRAM;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 60 "glfx.lpp"
debugPrint("shader"); glfxlval.lineno=glfxlineno; return SHADER;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "glfx.lpp"
debugPrint("interface"); glfxlval.lineno=glfxlineno; return INTERFACE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "glfx.lpp"
debugPrint("sampler"); glfxlval.lineno=glfxlineno; glfxlval.strs[0]=glfxtext; return SAMPLER;
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 63 "glfx.lpp"
{
                                                    debugPrint("include");
                                                    string tmp(glfxtext);
                                                    size_t firstLoc=tmp.find('"')+1;
                                                    size_t secondLoc=tmp.find('"', firstLoc);
                                                    glfxlval.strs[0]=tmp.substr(firstLoc, secondLoc-firstLoc);
                                                    glfxlval.lineno=glfxlineno-1; // flex has already jumped one line, since \n was eaten
                                                    return INCLUDE;
                                                }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("storageType"); glfxlval.strs[0]=glfxtext; return STORAGET;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("vs"); glfxlval.sType=VS; return SHADER_TYPE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("tc"); glfxlval.sType=TC; return SHADER_TYPE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("te"); glfxlval.sType=TE; return SHADER_TYPE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("gs"); glfxlval.sType=GS; return SHADER_TYPE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("fs"); glfxlval.sType=FS; return SHADER_TYPE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("num"); glfxlval.num=atoi(glfxtext); return NUM;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("float"); glfxlval.fnum=atof(glfxtext); return FLOAT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("storageQualifier"); glfxlval.lineno=glfxlineno; glfxlval.strs[0]=glfxtext; return STORAGEQ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("true"); glfxlval.num=1; return NUM;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("false"); glfxlval.num=0; return NUM;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Identificator"); glfxlval.lineno=glfxlineno; glfxlval.strs[0]=glfxtext; return IDENTIFIER;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Left parenthesis"); return LP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Right parenthesis"); return RP;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Left braces"); return LB;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Right braces"); return RB;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("brackets"); return EMPTY_ARRAY_BRACKETS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 89 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Comma"); return COMMA;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 90 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Equals"); return EQUALS;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Semicolon"); return SC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {debugPrint("Colon"); return COLON;}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 93 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; // Single line comment
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 94 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; // Multiline comment
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 95 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "glfx.lpp"
if(gLexPassthrough) gEffect->m_sharedCode<<glfxtext; else {errLex(glfxtext);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "glfx.lpp"
ECHO;
	YY_BREAK
#line 1622 "glfxScanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed glfxin at a new source and called
			 * glfxlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = glfxin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( glfxwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * glfxtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of glfxlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					glfxrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			glfxrestart(glfxin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) glfxrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = yy_start_state_list[(yy_start)];

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		yy_current_state += yy_current_state[(*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1)].yy_nxt;
		if ( yy_current_state[-1].yy_nxt )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register int yy_c = 1;
	register yyconst struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	if ( ! yy_is_jam )
		{
		if ( yy_current_state[-1].yy_nxt )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		}

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up glfxtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --glfxlineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					glfxrestart(glfxin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( glfxwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve glfxtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    glfxlineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void glfxrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        glfxensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            glfx_create_buffer(glfxin,YY_BUF_SIZE );
	}

	glfx_init_buffer(YY_CURRENT_BUFFER,input_file );
	glfx_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void glfx_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		glfxpop_buffer_state();
	 *		glfxpush_buffer_state(new_buffer);
     */
	glfxensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	glfx_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (glfxwrap()) processing, but the only time this flag
	 * is looked at is after glfxwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void glfx_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	glfxin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE glfx_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) glfxalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in glfx_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) glfxalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in glfx_create_buffer()" );

	b->yy_is_our_buffer = 1;

	glfx_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with glfx_create_buffer()
 * 
 */
    void glfx_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		glfxfree((void *) b->yy_ch_buf  );

	glfxfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a glfxrestart() or at EOF.
 */
    static void glfx_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	glfx_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then glfx_init_buffer was _probably_
     * called from glfxrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void glfx_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		glfx_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void glfxpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	glfxensure_buffer_stack();

	/* This block is copied from glfx_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from glfx_switch_to_buffer. */
	glfx_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void glfxpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	glfx_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		glfx_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void glfxensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)glfxalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in glfxensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)glfxrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in glfxensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE glfx_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) glfxalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in glfx_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	glfx_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to glfxlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       glfx_scan_bytes() instead.
 */
YY_BUFFER_STATE glfx_scan_string (yyconst char * yystr )
{
    
	return glfx_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to glfxlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE glfx_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) glfxalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in glfx_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = glfx_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in glfx_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up glfxtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		glfxtext[glfxleng] = (yy_hold_char); \
		(yy_c_buf_p) = glfxtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		glfxleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int glfxget_lineno  (void)
{
        
    return glfxlineno;
}

/** Get the input stream.
 * 
 */
FILE *glfxget_in  (void)
{
        return glfxin;
}

/** Get the output stream.
 * 
 */
FILE *glfxget_out  (void)
{
        return glfxout;
}

/** Get the length of the current token.
 * 
 */
int glfxget_leng  (void)
{
        return glfxleng;
}

/** Get the current token.
 * 
 */

char *glfxget_text  (void)
{
        return glfxtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void glfxset_lineno (int  line_number )
{
    
    glfxlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see glfx_switch_to_buffer
 */
void glfxset_in (FILE *  in_str )
{
        glfxin = in_str ;
}

void glfxset_out (FILE *  out_str )
{
        glfxout = out_str ;
}

int glfxget_debug  (void)
{
        return glfx_flex_debug;
}

void glfxset_debug (int  bdebug )
{
        glfx_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from glfxlex_destroy(), so don't allocate here.
     */

    /* We do not touch glfxlineno unless the option is enabled. */
    glfxlineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    glfxin = stdin;
    glfxout = stdout;
#else
    glfxin = (FILE *) 0;
    glfxout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * glfxlex_init()
     */
    return 0;
}

/* glfxlex_destroy is for both reentrant and non-reentrant scanners. */
int glfxlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		glfx_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		glfxpop_buffer_state();
	}

	/* Destroy the stack itself. */
	glfxfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * glfxlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *glfxalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *glfxrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void glfxfree (void * ptr )
{
	free( (char *) ptr );	/* see glfxrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 97 "glfx.lpp"



void debugPrint(const char* name)
{
#ifdef DEBUG_PRINT
    cerr<<name<<" - "<<glfxtext<<endl;
#endif
}

void errLex(const char* tok)
{
    ostringstream errMsg;
    
    errMsg<<"0("<<glfxlineno<<") : error: Unkown token '"<<tok<<'\'';
    throw errMsg.str();
}

string glfxreadblock(unsigned char openChar, unsigned char closeChar)
{
    string str;
    int braceBalance=0;
    unsigned char c;
    bool done=false;
    do {
        c=(unsigned char)yyinput();
        str+=c;
        if(c==0)
            throw "Brace balance error\n";
        else if(c==openChar)
            braceBalance++;
        else if(c==closeChar) {
            braceBalance--;
            if(braceBalance<0)
                throw "Brace balance error\n";
            else if(braceBalance==0)
                done=true;
        }
    } while(!done);
    return str;
}

